version: "3.9"

services:
  bot:
    build: .
    container_name: bot-financeiro
    env_file:
      - .env
    networks:
      - bot_network  # <-- Certifique-se de que a rede está referenciada aqui
    restart: always

networks:
  bot_network:  # <-- Certifique-se de que a rede está declarada aqui
    driver: bridge
