version: "3.9"

services:
  bot:
    build: .
    container_name: bot-financeiro
    environment:
      - RUNNING_IN_DOCKER=true
    networks:
      - bot_network
    restart: always

networks:
  bot_network:
    driver: bridge
