apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot-financeiro
  ports:
    - protocol: TCP
      port: 8080  # Porta externa do cluster
      targetPort: 8080  # Porta do container
  type: ClusterIP
